fos_rest:
    param_fetcher_listener: true
    body_listener:
        default_format: json
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'html' }
    versioning: true
    view:
        view_response_listener: 'force'
    service:
        serializer:           null
        view_handler:         fos_rest.view_handler.default
        validator:            validator

