version: "3.9"
services:
    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
            - ../db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: leboncoin
            MYSQL_USER: admin 
            MYSQL_PASSWORD: admin
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    www:
        build: .
        container_name: www_docker_symfony
        ports:
            - "8741:80"
        restart: always
        networks:
            - dev
        volumes:
            - ../:/var/www
            - ./etc/apache:/etc/apache2/sites-enabled
networks:
    dev:



volumes:
    db-data:
